services:
  sol:
    build: .
    entrypoint: app 
    environment:
      GIN_MODE: "release"
    depends_on:
      - component
    stdin_open: true
    tty: true
    networks:
      vs-network:

  component:
    build: .
    entrypoint: app -sleep -killSol
    environment:
      GIN_MODE: "release"
    stdin_open: true
    tty: true
    networks:
      vs-network:

networks:
  vs-network:
    external: false
