services:
  sol:
    build: .
    entrypoint: /usr/src/app/compose_entrypoint.sh
    environment:
      GIN_MODE: "release"
    stdin_open: true
    tty: true
    networks:
      vs-network:

  component:
    build: .
    entrypoint: /usr/src/app/compose_entrypoint.sh NotSol
    environment:
      GIN_MODE: "release"
    stdin_open: true
    tty: true
    networks:
      vs-network:

networks:
  vs-network:
    external: false
