services:
  sol:
    build: .
    entrypoint: app 
    stdin_open: true
    tty: true
    networks:
      vs-network:
        # ipv4_address: 172.18.0.1

  component:
    build: .
    entrypoint: app -sleep -killSol
    stdin_open: true
    tty: true
    networks:
      vs-network:
        # ipv4_address: 172.18.0.2

networks:
  vs-network:
    driver: host
