services:
  sol:
    build: .
    entrypoint: screen -mS app app 
    environment:
      GIN_MODE: "release"
    stdin_open: true
    tty: true
    networks:
      vs-network:
    depends_on:
      - component

  component:
    build: .
    entrypoint: screen -mS app app -sleep -killSol
    environment:
      GIN_MODE: "release"
    stdin_open: true
    tty: true
    networks:
      vs-network:

networks:
  vs-network:
    external: false
