services:
  sol:
    build: .
    entrypoint: /usr/src/app/compose_entrypoint.sh
    tty: true
    networks:
      vs-network:

  component:
    build: .
    entrypoint: /usr/src/app/compose_entrypoint.sh NotSol
    tty: true
    networks:
      vs-network:
    deploy:
      mode: replicated
      replicas: 3

networks:
  vs-network:
    external: false
